output_dir: /home/ar0241/scratch/twins/

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.lora_llama3_2_1b
  lora_attn_modules: ['q_proj', 'v_proj', 'output_proj']
  apply_lora_to_mlp: True
  lora_rank: 64
  lora_alpha: 128
  lora_dropout: 0.0

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /home/ar0241/scratch/torchtune_models/Llama-3.2-1B-Instruct/original/tokenizer.model
  max_seq_len: null

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /home/ar0241/scratch/torchtune_models/Llama-3.2-1B-Instruct/
  checkpoint_files: [model.safetensors]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_2
resume_from_checkpoint: False
save_adapter_weights_only: False

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.01
  lr: 1e-4  # Kept from previous suggestion
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Training
epochs: 3
max_steps_per_epoch: null
gradient_accumulation_steps: 8
compile: False

train_dataloader:
  _component_: torchtune.datasets.instruct_dataset
  source: "json"
  data_files: "/home/ar0241/scratch/twins/ptwindat_train.json"
  shuffle: true
  batch_size: 8
  num_workers: 4

dataset:
  _component_: torchtune.datasets.instruct_dataset
  source: "json"
  data_files: "/home/ar0241/scratch/twins/ptwindat_train.json"
  description: "Twin zygosity prediction dataset formatted for instruction tuning with binary outputs"

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True

wandb:
  api_key: "9d5d313579e3f51aecbf2f563fee7989c1b540b8"
  project: "zygosity-twin-llama"
  entity: "llms-are-the-new-glms"

# Environment
device: cuda
dtype: fp32

# Activations Memory
enable_activation_checkpointing: False
enable_activation_offloading: False

# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False
  output_dir: ${output_dir}/profiling_outputs
  cpu: True
  cuda: True
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1

hf_token: "token_here"
seed: 1234
shuffle: True
batch_size: 4


